config/routes.rb
Rails.application.routes.draw do
  root 'owners#index'
  resources :owner, only: [] do
    resources :puppies, only: [:new, :create, :show]
  end

  resources :puppies, only: [:show] do
    resources :toys, only: [:create]
    resources :appointments, only: [:create]
  end
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  validates :time, presence: true
  belongs_to :vet
  belongs_to :puppy
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :puppies
end

app/models/puppy.rb
class Puppy < ActiveRecord::Base
  validates :name, presence: true
  has_many :vets, through: :appointments
  has_many :appointments

  belongs_to :owner
  has_many :toys
end

app/models/toy.rb
class Toy < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :puppy
end

app/models/vet.rb
class Vet < ActiveRecord::Base
  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def create
    @appointment = Appointment.new(appointment_params.merge(puppy_id: params[:puppy_id]))

    if @appointment.save
      flash[:notice] = "Poor puppy"
      redirect_to puppy_path(params[:puppy_id])
    else
      render "puppies/show"
    end
  end

  private

  def appointment_params
    params.require(:appointment).permit(:time, :vet_id)
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = Owner.all
  end
end

app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
  def new
    @owner = Owner.find(params[:owner_id])
    @puppy = Puppy.new
  end

  def create
    @owner = Owner.find(params[:owner_id])
    @puppy = Puppy.new(puppy_params.merge(owner_id: @owner.id))
    if @puppy.save
      flash[:notice] = "You just got a puppy"
      redirect_to owner_puppy_path(@owner, @puppy)
    else
      render :new
    end
  end

  def show
    @appointment = Appointment.new
    @puppy = Puppy.find(params[:id])
    @toy = Toy.new
  end

  private

  def puppy_params
    params.require(:puppy).permit(:name)
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  def create
    @puppy = Puppy.find(params[:puppy_id])
    @toy = @puppy.toys.new(toy_params)
    if @toy.save
      flash[:notice] = "Yay toys!"
      redirect_to puppy_path(@puppy)
    else
      render "puppies/show"
    end
  end

  private

  def toy_params
    params.require(:toy).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PuppiesApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/owners/index.html.haml
- @owners.each do |owner|
  = link_to owner.name, new_owner_puppy_path(owner)

app/views/puppies/new.html.haml
= form_for([@owner, @puppy]) do |f|

  = f.label :name
  = f.text_field :name

  = f.submit

app/views/puppies/show.html.haml
= @puppy.name

= form_for([@puppy, @toy]) do |f|

  = f.label :name
  = f.text_field :name

  = f.submit

%ul
-@puppy.toys.each do |toy|
  %li=toy.name

%br
%br



= form_for([@puppy, @appointment]) do |f|

  = f.label :vet_id, "Vet Name"
  = f.collection_select(:vet_id, Vet.all, :id, :name)

  = f.label :time
  = f.time_select :time

  = f.submit

%ul
- @puppy.appointments.each do |appointment|
  %li= "#{appointment.time.strftime("%m-%d-%Y")} with #{appointment.vet.name}"